### ISSUE TITLE
gommit check message never validate matchers

### ISSUE THREAD

**Issue by Geoffrey42** [antham/gommit#58]
**Describe the bug**

gommit doesn't validate any of the message of my commits even when they seems to fit ```.gommit.toml```

**To Reproduce**
1. Based on this ```.gommit.toml```

```toml
[config]
exclude-merge-commits=true
check-summary-length=true
summary-length=50

[matchers]
all="(?:ref|feat|test|fix|style)\\(.*?\\) : .*?\n(?:\n?(?:\\* |  ).*?\n)*"

[examples]
a_simple_commit="""
[feat|test|ref|fix|style](module) : A commit message
"""
an_extended_commit="""
[feat|test|ref|fix|style](module) : A commit message

* first line
* second line
* and so on...
"""
```

2. if I run:

```shell
gommit check message "test(git) : add .gommit.toml"
```

3. I get:

```shell
----

Message  : 
           test(git) : add .gommit.toml

Error(s) : - No template match commit message

=======

Your message must match one of those following patterns :

----

An extended commit : 

[feat|test|ref|fix|style](module) : A commit message

* first line
* second line
* and so on...

----

A simple commit : 

[feat|test|ref|fix|style](module) : A commit message
```

**Expected behavior**

I expect something closer to *Everything is ok*.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave when I downloaded gommit the first time. I upgraded to MacOS Catalina 10.15 since.
 - Shell: zsh
- gommit version: 2.2.0

**Additional context**

The first time I tried ```gommit``` few weeks ago, everything works fine. I even add a lot of stuff to the sample ```.gommit.toml```:

```toml
[config]
exclude-merge-commits=true
check-summary-length=true
summary-length=80

[matchers]
all="(?:ref|feat|test|fix|style|ci|perf|chores|docs|revert|build)\\(.*?\\): .*?\n(?:\n?(?:\\* |  ).*?\n)*"

[examples]
a_simple_commit="""
[feat|test|ref|fix|style|perf|chores|docs|revert|ci|build](module): A commit message
"""
an_extended_commit="""
[feat|test|ref|fix|style|perf|chores|docs|revert|ci|build](module): A commit message
* first line
* second line
* and so on...
"""
```

Again, everything worked fine. But few days ago I notice that I was unable to validate any of my commits since. Is this linked to my OS upgrade ? 

By the way **great job** with gommit, for the time it works for me it was a relief in my workflow.
