### ISSUE TITLE
Ignore git revert messages

### ISSUE THREAD

**Issue by dijonkitchen** [antham/gommit#72]
Sometimes, a commit can be within the proper length, but when you use `git revert` the auto commit message is over the set length. There should probably be a configuration for toggling that on or off just like merge commits.

**Comment by antham** [comment]
Hi, thanks for reporting.

You could simply add a matcher for this case : 

```toml
[matchers]
revert="Revert.+?\n(?:\n?.+)+(?:\n)?"
```
